Controllers/BuyController.cs
using AspNetCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project3.Models;
using System.Data;
using System.Security.Claims;

namespace Project3.Controllers
{
    public class BuyController : Controller
    {
        public readonly stockContext db;
        public readonly ISession session;
        public BuyController(stockContext _db, IHttpContextAccessor httpContextAccessor) 
        {
            db = _db;
            session = httpContextAccessor.HttpContext.Session;
        }
        public IActionResult Index()
        {

            HttpContext.Session.GetString("Cname");
            ViewBag.email = HttpContext.Session.GetString("Cname");
            ViewBag.a= HttpContext.Session.GetString("StName");
            if (ViewBag.email != null)
            {
                //var a = db.Purchases.Include(i => i.PidNavigation).ToList();
                var a=db.Products.ToList();
                return View(a);
            }
            else
            {
                return RedirectToAction("Loginc", "Customer");
            }
        }
        [HttpGet]
        public IActionResult PlaceOrder(int id)
        {
            ViewBag.s = new SelectList(db.Products, "Pid", "Pname");
            var x = (from i in db.Products
                    where i.Pid == id
                    select i).SingleOrDefault();
            return View(x);
        }
        [HttpPost]
        public IActionResult PlaceOrder(int id,Product p)
        {
            //ViewBag.s = new SelectList(db.Purchases, "Pid", "Pid");
            try
            {
                Random r = new Random();

                Product x = (from i in db.Products
                             where i.Pid == id
                             select i).SingleOrDefault();
                Pur pr = new();
                pr.Puid = r.Next();
                pr.Pname = x.Pname;
                pr.Pid = x.Pid;

                if (x.Pquantity == 0)
                {
                    ViewBag.Message = "Product not available";
                    return View();
                }
                if (p.Pquantity < x.Pquantity && p.Pquantity > 0)
                {
                    x.Pquantity = x.Pquantity - p.Pquantity;
                    pr.Purquantity = p.Pquantity;
                    pr.TotalPrice = pr.Purquantity * (int)x.Pcost;
                    pr.Cid = session.GetInt32("Cid");
                    ViewBag.name = session.GetString("Cname");
                    db.Purs.Add(pr);
                    db.SaveChanges();
                    ViewBag.pur = pr;
                    return RedirectToAction("bill", pr);
                }
                else
                {
                    ViewBag.Message = "Enter purchase quantity that is lesser than the product quantity";
                    return View();

                }
            }
            catch(Exception ex)
            {
                ViewBag.Message = ex.Message;
                return View();
            }
            
            
            }

        
        public IActionResult bill(Pur p)
        {         

            return View(p);
        }
        public IActionResult allpur()
        {
            ViewBag.name = session.GetString("Cname");
            List<Pur> a = db.Purs.Where(x => x.Cid == session.GetInt32("Cid")).ToList();
            return View(a);

        }
        public IActionResult adminpur()
        {
            
            var a = db.Purs.ToList();
            return View(a);

        }
       

    }



}

Controllers/LoginController.cs
using Microsoft.AspNetCore.Mvc;
using Project3.Models;

namespace Project3.Controllers
{
    public class LoginController : Controller
    {
        public readonly stockContext db;
        public readonly ISession session;
        public LoginController(stockContext _db, IHttpContextAccessor httpContextAccessor)
        {
            db = _db;
            session = httpContextAccessor.HttpContext.Session;
        }

        public IActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Login(Stockist p)
        {
            var res = (from i in db.Stockists
                       where (i.StName == p.StName) && (i.Password == p.Password)
                       select i).SingleOrDefault();
            if (res != null)
            {
                session.SetString("StName", res.StName);
                return RedirectToAction("Index");

            }
            else
            {
                ViewBag.Message = "Invalid Username";
                return View();
            }
        }
        public IActionResult Index()
        {
            ViewBag.name = HttpContext.Session.GetString("StName");
            return View();
        }
        public IActionResult cview()
        {
            return View();
        }
        [HttpPost]
        public IActionResult cview(Stockist p)
        {
            var res = (from i in db.Stockists
                       where (i.StName == p.StName) && (i.Password == p.Password)
                       select i).SingleOrDefault();
            if (res != null)
            {
                session.SetString("StName", res.StName);
                return RedirectToAction("Index", "Customer");

            }
            else
            {
                ViewBag.Message = "Invalid Username";
                return View();
            }
            
        }
        public IActionResult Logout() 
        {
            session.Clear();
            return RedirectToAction("Index", "Home");
        }
        
    }
    
    }

Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Project3.Models;

namespace Project3.Controllers
{
    public class ProductController : Controller
    {
        private readonly stockContext _context;
        public readonly ISession session;
        


        public ProductController(stockContext context,IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            session = httpContextAccessor.HttpContext.Session;

        }

        // GET: Product
        

        public async Task<IActionResult> Index()
        {
            HttpContext.Session.GetString("StName");
            ViewBag.email = HttpContext.Session.GetString("StName");
            if (ViewBag.email != null)
            {
                return View(await _context.Products.ToListAsync());
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }

        // GET: Product/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            HttpContext.Session.GetString("StName");
            ViewBag.email = HttpContext.Session.GetString("StName");
            if (ViewBag.email != null)
            {
                if (id == null || _context.Products == null)
                {
                    return NotFound();
                }

                var product = await _context.Products
                    .FirstOrDefaultAsync(m => m.Pid == id);
                if (product == null)
                {
                    return NotFound();
                }

                return View(product);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
            
        }

        // GET: Product/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Product/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Pid,Pname,Pcost,Pquantity")] Product product)

        {
            if (ModelState.IsValid)
            {

                HttpContext.Session.GetString("StName");
                ViewBag.email = HttpContext.Session.GetString("StName");
                if (ViewBag.email != null)
                {
                    var r = (from i in _context.Products
                             where (i.Pname == product.Pname) || (i.Pid == product.Pid)
                             select i).SingleOrDefault();
                    if (r == null)
                    {
                        _context.Add(product);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        ViewBag.Message = "The Product already exists";
                        return View(product);

                    }
                }

                else
                {
                    return RedirectToAction("Login", "Login");
                }
            }
            
            return View(product);
        }

        // GET: Product/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            HttpContext.Session.GetString("StName");
            ViewBag.email = HttpContext.Session.GetString("StName");
            if (ViewBag.email != null)
            {
                if (id == null || _context.Products == null)
                {
                    return NotFound();
                }

                var product = await _context.Products.FindAsync(id);
                if (product == null)
                {
                    return NotFound();
                }
                return View(product);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }

        // POST: Product/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Pid,Pname,Pcost,Pquantity")] Product product)
        {
            if (ModelState.IsValid)
            {
                HttpContext.Session.GetString("StName");
                ViewBag.email = HttpContext.Session.GetString("StName");
                if (ViewBag.email != null)
                {
                    if (id != product.Pid)
                    {
                        return NotFound();
                    }

                    if (ModelState.IsValid)
                    {
                        try
                        {
                            _context.Update(product);
                            await _context.SaveChangesAsync();
                        }
                        catch (DbUpdateConcurrencyException)
                        {
                            if (!ProductExists(product.Pid))
                            {
                                return NotFound();
                            }
                            else
                            {
                                throw;
                            }
                        }
                        return RedirectToAction(nameof(Index));
                    }
                    return View(product);
                }
                else
                {
                    return RedirectToAction("Login", "Login");
                }
            }
            else
            {
                return View(product);
            }
        }

        // GET: Product/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {

            HttpContext.Session.GetString("StName");
            ViewBag.email = HttpContext.Session.GetString("StName");
            if (ViewBag.email != null)
            {
                if (id == null || _context.Products == null)
                {
                    return NotFound();
                }

                var product = await _context.Products
                    .FirstOrDefaultAsync(m => m.Pid == id);
                if (product == null)
                {
                    return NotFound();
                }

                return View(product);
            }
            else
            {
                return RedirectToAction("Login", "Login");
            }
        }

        // POST: Product/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (ModelState.IsValid)
            {

                HttpContext.Session.GetString("StName");
                ViewBag.email = HttpContext.Session.GetString("StName");
                if (ViewBag.email != null)
                {
                    if (_context.Products == null)
                    {
                        return Problem("Entity set 'stockContext.Products'  is null.");
                    }
                    var product = await _context.Products.FindAsync(id);
                    if (product != null)
                    {
                        _context.Products.Remove(product);
                    }

                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    return RedirectToAction("Login", "Login");
                }
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        private bool ProductExists(int id)
        {
          return _context.Products.Any(e => e.Pid == id);
        }
    }
}

Views/Login/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
           <h1> Hello @ViewBag.name</h1>
            <body style="background-image:url(https://t3.ftcdn.net/jpg/00/96/24/36/360_F_96243602_hgZuimFj1cJFqrrvERCnsq7NZ8VRZ7y7.jpg);background-repeat:no-repeat;background-size:cover">


            <div class="form-group">
                <input type="submit" value="See Product"  asp-action="Index" asp-controller="Product"/>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Get Customer Details" asp-action="adminpur" asp-controller="Buy" />
            </div><br />

            <div class="form-group">
                <input type="submit" value="Back" asp-action="Login" asp-controller="Login" />
            </div>
            </body>
        </form>
    </div>
</div>

Views/Login/Login.cshtml
@model Project3.Models.Stockist

@{
    ViewData["Title"] = "Login";
}

<h1><div style="color:black">ADMIN LOGIN</div></h1>
<body style="background-image:url(https://t3.ftcdn.net/jpg/00/96/24/36/360_F_96243602_hgZuimFj1cJFqrrvERCnsq7NZ8VRZ7y7.jpg);background-repeat:no-repeat;background-size:cover">


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @{
                if (@ViewBag.Message != null)
                {
                           <h6>
                            <div style="color:red">
                            @ViewBag.Message
                            </div>

                            </h6>
                }

            }
            <div class="form-group">
                <label asp-for="StName" class="control-label"></label>
                <input asp-for="StName" class="form-control" />
                <span asp-validation-for="StName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" type="password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div><br />
            
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div><br />

                
        </form>
    </div>
</div>

@*<div>
    <a asp-action="Index" asp-controller="Home">Back to Home</a>
</div>*@
</body>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Login/cview.cshtml
@model IEnumerable<Project3.Models.Customer>

@{
    ViewData["Title"] = "cview";
}

<h1>cview</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<body style="background-image:url(https://t3.ftcdn.net/jpg/00/96/24/36/360_F_96243602_hgZuimFj1cJFqrrvERCnsq7NZ8VRZ7y7.jpg);background-repeat:no-repeat;background-size:cover">

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pass)
            </th>
            @*<th>
                @Html.DisplayNameFor(model => model.Cpass)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pass)
            </td>
            @*<td>
                @Html.DisplayFor(modelItem => item.Cpass)
            </td>*@
            @*<td>
                <a asp-action="Edit" asp-route-id="@item.Cid">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Cid">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Cid">Delete</a>
            </td>*@
        </tr>
}
        <div class="form-group">
            <input type="submit" value="Get Customer Details" class="btn btn-primary" />
        </div>
    </tbody>
</table>
</body>